FROM registry.fedoraproject.org/fedora:latest

RUN echo "trigger rebuild 2023-05-30 21:44:00"

RUN dnf upgrade -y --refresh
RUN dnf install -y dnf5 dnf5-plugins

RUN dnf5 install -y \
  systemd \
  systemd-udev

RUN dnf5 install -y openssh-server && \
  systemctl enable sshd

RUN dnf5 install -y \
  'dnf-command(copr)' \
  tmux vim \
  btrfs-progs \
  iproute NetworkManager-tui NetworkManager-wifi wpa_supplicant

RUN dnf5 remove -y 'plymouth*'

COPY hostname /etc/hostname

RUN dnf copr enable -y maggu2810/op6

RUN dnf5 install -y device-oneplus-enchilada

RUN systemctl enable pd-mapper
RUN systemctl enable qbootctl-mark-boot-successful.service
RUN systemctl enable tqftpserv
RUN systemctl enable rmtfs

RUN echo 'root:654321' | chpasswd 

RUN groupadd -g 1000 unpriv && \
  useradd -g 1000 -G wheel -m -u 1000 unpriv && \
  echo 'unpriv:123456' | chpasswd

ENTRYPOINT ["/bin/bash", "-l", "-i"]

