FROM registry.fedoraproject.org/fedora:latest

RUN dnf install -y dnf5 dnf5-plugins
RUN dnf5 install -y dnf5 dnf5-plugins

RUN dnf5 install -y tmux vim

#RUN dnf5 group install -y --with-optional phosh-desktop
RUN dnf install -y @phosh-desktop-environment

RUN echo 'root:654321' | chpasswd 

RUN groupadd -g 1000 unpriv && \
  useradd -g 1000 -G wheel -m -u 1000 unpriv && \
  echo 'unpriv:123456' | chpasswd

RUN echo '/dev/mapper/sda17p2 / ext4 rw,relatime 0 0' > /etc/fstab

RUN dnf5 install -y openssh-server && \
  systemctl enable sshd

RUN dnf5 remove -y 'plymouth*'

RUN dnf copr enable -y maggu2810/op6

RUN dnf5 install -y pd-mapper
RUN systemctl enable pd-mapper

RUN dnf5 install -y qbootctl
RUN systemctl enable qbootctl-mark-boot-successful.service

# DOWNLOAD FILE: https://github.com/maggu2810/op6-containers/releases/download/oneplus-enchilada-pmos-ui-none/oneplus-enchilada-pmos-ui-none.tgz
# pmbootstrap init: edge, for enchilada with user interface none
# pmbootstrap install
# pmbootstrap export
# install android-tools for simg2img
# simg2img /tmp/postmarketOS-export/oneplus-enchilada.img oneplus-enchilada.img
# export IMG_PATH="${PWD}/oneplus-enchilada.img"
# mkdir root
# sudo mount /dev/loop0p2 root
# sudo mount /dev/loop0p1 root/boot
# sudo tar czpf oneplus-enchilada.tgz -C root/ .
# sudo umount root/boot root/
# rmdir root
# rm oneplus-enchilada.img
COPY oneplus-enchilada-pmos-ui-none.tgz /tmp/
RUN mkdir /pmos
RUN tar xzpf /tmp/oneplus-enchilada-pmos-ui-none.tgz -C /pmos
RUN rm /tmp/oneplus-enchilada-pmos-ui-none.tgz


# MOVE UP - SOME TIME
RUN dnf5 install -y 'dnf-command(copr)'


COPY pmos-get-kernel-modules-fimware /usr/local/bin/pmos-get-kernel-modules-fimware
RUN chown 0:0 /usr/local/bin/pmos-get-kernel-modules-fimware && \
    chmod 0755 /usr/local/bin/pmos-get-kernel-modules-fimware

ENTRYPOINT ["/bin/bash", "-l", "-i"]

