FROM docker.io/maggu2810/op6-fedora:latest

#RUN dnf5 group install -y --with-optional phosh-desktop
RUN dnf install -y @phosh-desktop-environment

RUN mkdir -p /var/lib/AccountsService/users/ && \
    echo '[User]' > unpriv && \
    echo 'Session=phosh' >> unpriv

ENTRYPOINT ["/bin/bash", "-l", "-i"]

