FROM docker.io/maggu2810/op6-fedora:latest

#RUN dnf5 group install -y --with-optional phosh-desktop
RUN dnf install -y @phosh-desktop-environment

# Auto login, default session: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_the_desktop_environment_in_rhel_8/managing-user-sessions_using-the-desktop-environment-in-rhel-8
# Auto login: https://help.gnome.org/admin/system-admin-guide/stable/login-automatic.html.en
# The list of valid session names can be found by listing /usr/share/xsessions/*.desktop for X's sessions and /usr/share/wayland-sessions/*.desktop for Wayland's. 
RUN mkdir -p /etc/accountsservice/user-templates/ && \
    cp /usr/share/accountsservice/user-templates/standard /etc/accountsservice/user-templates/standard && \
    sed 's:^Session=$:Session=phosh:g' -i /etc/accountsservice/user-templates/standard

ENTRYPOINT ["/bin/bash", "-l", "-i"]

